[project]
name = "astro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astropy>=8.0.0",
    "jdaviz>=5.0.2",
    "matplotlib>=3.11.0",
    "numpy>=2.4.6",
    "sep>=1.4.0",
    "setuptools<81",
    "specutils>=2.4.0",
    "zap",
]

[tool.uv.sources]
zap = { path = "libs/zap", editable = true }
